name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - staging
      - production

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install aftman
        uses: ok-nick/setup-aftman@v0.4.2
        with:
          version: v1.0.0
          path: .
          cache: false
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Lint
        run: |
          selene ./Core
          selene ./Library
          selene ./src
  style:
    name: Styling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install stylua-action
        uses: JohnyMorganz/stylua-action@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --check .
